definitions:
  schema.User:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /registration:
    post:
      consumes:
      - application/json
      description: Получить список всех пользователей в системе
      parameters:
      - description: registration
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/schema.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.User'
      summary: Получить список пользователей
      tags:
      - Users
swagger: "2.0"
